# get api_id & api_hash from my.telegram.org
api_id: '29721235'
api_hash: 'a0045602d212e62001bd1ae234b04043'
# 13 digit channel id startswith - like -111.......
dump_id: '-1002105734368'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOK4Bu4BL5Y2CQX21_-iYIXhWgrDhbDBm3FczzjW81ugek3loiDQeWidSbIXAKNgKV6-Lh-_iyLBKbRAmnKBnqOFY_kmWN8cqnUy62P1_zn_cxUXhOsbWSAJ8WtIirpJjOhPATj88oo1V8rcnRsBLpeb-k3Oi65Iof8Yd7o4dTac8dk5WDB-j85-1WVSUQOYa0n2ogBCs6tXsbRYYvrMINaqnRUMSZE799R7K5M1v8HJx0iCauFCEdoWe-rnAUxTz5QSaKpHDs4EVSSAeLJzHa6BVm0NdgyOnvsVJz3ALE2GHpQHf7-KMF0v8slzfxoqF8cir45WmVGmu8VAmlLEV0efOrd8='
